#! /usr/bin/env ruby

require 'bundler'
require 'aws-sdk-codecommit'

aws_cc_client = Aws::CodeCommit::Client.new(
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  region: ENV['AWS_REGION'],
)

github_repos = ARGV
aws_cc_repos = []
next_token = nil

loop do
  aws_response = aws_cc_client.list_repositories(next_token: next_token)
  aws_cc_repos << aws_response.repositories.map(&:repository_name)
  next_token = aws_response.next_token
  break unless next_token
end

missing = github_repos - aws_cc_repos.flatten

missing.each do |r|
  puts "Creating #{r}..."
  aws_cc_client.create_repository({repository_name: r})
end
