#!/usr/bin/env ruby

require 'bundler/setup'
require 'aws-sdk-core'
require 'json'

creds = Aws::STS::Client
  .new(region: 'eu-west-2')
  .assume_role(
    role_arn: ENV.fetch('ROLE_ARN'),
    role_session_name: 'jenkins'
  )
  .credentials


puts <<~CREDS
  export AWS_ACCESS_KEY_ID='#{creds.access_key_id}'
  export AWS_SECRET_ACCESS_KEY='#{creds.secret_access_key}'
  export AWS_SESSION_TOKEN='#{creds.session_token}'
CREDS
